Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["de"] = {
    ["criminalRecord"] = "Strafregister",
    ["recordOf"] = "Schließfach von",
    ["username"] = "Name der Person",
    ["addUpperCase"] = "ANZEIGE",
    ["infractionReason"] = "Grund für die Straftat",
    ["create"] = "Erstellen",
    ["cancel"] = "Abbrechen",
    ["licenseplate"] = "Nummernschild",
    ["search"] = "Suche",
    ["noVehiclesFound"] = "Keine Fahrzeuge gefunden",
    ["reportText"] = [[Frau Staatsanwältin, Herr Staatsanwalt,

    Ich, der Unterzeichnete (Vor- und Nachname), geboren am (Geburtsdatum) am (Geburtsort), der den Beruf (Beruf) ausübt, teile Ihnen mit, dass ich Anzeige gegen (Vor- und Nachname / Name des Unternehmens / Name der Organisation / oder X, falls unbekannt), wohnhaft in (Name der Adresse der betreffenden Person oder des Unternehmens), wegen (Qualifikation der Straftat) erstatte.

    Am (Datum des Ereignisses) war ich tatsächlich Opfer des folgenden Sachverhalts: (geben Sie so genau wie möglich die Einzelheiten des Sachverhalts sowie den Ort, an dem er sich ereignet hat, die Uhrzeit des Ereignisses und die an der Zuwiderhandlung beteiligten Personen an). Ich füge diesem Schreiben alle Dokumente/Fotos/Beweise bei, die für den weiteren Verlauf des Falles nützlich sein könnten (bitte fügen Sie Kopien und keine Originale bei).

    Mehrere Personen waren Zeugen der oben genannten Straftat. Es handelt sich um Frau/Herr (Vor- und Nachname).

    Bitte nehmen Sie, sehr geehrte Frau, sehr geehrter Herr Staatsanwalt, den Ausdruck meiner besten Gefühle an.

    Unterschrift des Polizeibeamten]],
    ["unknown"] = "Unbekannt",
    ["delete"] = "Löschen",
    ["at"] = "Die",
    ["accusedName"] = "Angeklagter Name",
    ["save"] = "Speichern",
    ["prosecutor"] = "Staatsanwaltschaft",
    ["accused"] = "Anerkannt",
    ["date"] = "Datum",
    ["see"] = "Schauen",
    ["username2"] = "Name der Person",
    ["allComplaints"] = "Alle Beschwerden",
    ["moveX"] = "Verschiebung der X-Achse",
    ["moveY"] = "Verschiebung der Y-Achse",
    ["moveZ"] = "Verschiebung der Z-Achse",
    ["rotateX"] = "Drehung der X-Achse",
    ["rotateY"] = "Drehung der Y-Achse",
    ["rotateZ"] = "Drehung der Z-Achse",
    ["rotateYY"] = "Drehung der Y-Achse",
    ["width"] = "Breite",
    ["height"] = "Höhe",
    ["configureLicenseplate"] = "Wählen Sie das Fahrzeug \n um das Nummernschild zu konfigurieren",
    ["placeLicenseplate"] = "Bringen Sie das (1) Nummernschild \n Ihrem Fahrzeug an einem geeigneten Platz \n.",
    ["placeLicenseplate2"] = "Bringen Sie das (2) Nummernschild \n Ihrem Fahrzeug an einem geeigneten Platz \n.",
    ["undefined"] = "Sie haben nicht den richtigen Job, um auf den Computer zuzugreifen",
    ["youWon"] = "Du hast gewonnen",
    ["youAddPenality"] = "Sie haben eine Strafe hinzugefügt",
    ["cameraCenter"] = "Kamera-Zentrum",
    ["cameraSecurityOfCity"] = "Sicherheitskamera der Stadt",
    ["switchCamera"] = "Drücken Sie USE um die Kamera zu wechseln",
    ["cantDelete"] = "Sie können das nicht löschen",
    ["cantDoThat"] = "Das kannst du nicht tun",
    ["noSignal"] = "KEIN SIGNAL",
    ["connectionProblem"] = "Problem mit der Verbindung",
    ["computerMustBeHacked"] = "Der Computer muss gehackt werden, um eine Anwendung zu öffnen",
    ["cantAffordFine"] = "Sie haben nicht genug Geld, um die Strafe zu bezahlen",
    ["payFine"] = "Bezahlen Sie die Geldstrafe",
    ["confirm"] = "BESTÄTIGEN",
    ["category"] = "KATEGORIE",
    ["fineBook"] = "Schönes Buch",
    ["noPayFine"] = "Hat die Geldstrafe nicht bezahlt",
    ["personAlreadyHaveFine"] = "Diese Person hat bereits eine Geldstrafe",
    ["vehicleHaveFine"] = "Dieses Fahrzeug hat bereits eine Geldstrafe",
    ["vehicleCantReceiveFine"] = "Dieses Fahrzeug kann keine Geldstrafe haben",
    ["noGoodJob"] = "Sie haben nicht den richtigen Job, um eine Geldstrafe zu zahlen",
    ["userCantReceiveFine"] = "Sie können diesem Spieler keine Geldstrafe auferlegen",
    ["vehicleCantHaveFine"] = "Bei diesem Fahrzeug können keine Bußgelder erhoben werden.",
    ["richSanctions"] = "Sie können weitere Strafen verhängen",
    ["mustSelectPenality"] = "Sie müssen eine Strafe wählen",
    ["cantAddFineToHimVehicle"] = "Sie können Ihr Fahrzeug nicht mit einem Bußgeld belegen",
    ["noGoodJobToArrestuser"] = "Sie haben nicht den richtigen Job, um diese Person zu verhaften",
    ["cantArrestPlayer"] = "Sie können diese Person nicht verhaften",
    ["needHoldPlayerToArrest"] = "Du musst einen Spieler ins Gefängnis bringen",
    ["justPaid"] = "Du hast gerade bezahlt",
    ["cantAfford"] = "Sie haben nicht genug Geld für so etwas",
    ["arrestMenu"] = "Menü Verhaftung",
    ["name"] = "Name",
    ["price"] = "Preis",
    ["reason"] = "Motiv",
    ["pay"] = "Bezahlen",
    ["arrestedPlayersList"] = "Liste der Verhafteten",
    ["noArrestedPlayer"] = "Es wurde kein Spieler verhaftet",
    ["noJailPositions"] = "Es gibt keine Gefängnis position, kontaktiere einen Admin",
    ["weaponsList"] = "Liste der Waffen",
    ["confiscate"] = "KONFISZIEREN",
    ["youSurrender"] = "Du gibst Auf",
    ["youArrest"] = "Sie sind verhaftet",
    ["years"] = "Jahre",
    ["tooMuchEntities"] = "Sie haben zu viele Entities",
    ["spawnPropText"] = "Drücken Sie [USE], um ein Prop zu erzeugen.",
    ["youUnarrestBy"] = "Sie wurden freigelassen von",
    ["youArrestBy"] = "Sie wurden verhaftet von",
    ["youHaveArrest"] = "Sie haben verhaftet",
    ["policeCartrunk"] = "Polizei Kofferraum",
    ["cantDeleteSelfSanctions"] = "Du kannst deine Strafe nicht löschen",
    ["cantEditSelfSanctions"] = "Sie können Ihre Strafe nicht bearbeiten",
    ["seconds"] = "Sekunden",
    ["cameraName"] = "Name der Kamera",
    ["cameraConfiguration"] = "Kamera-Konfiguration",
    ["press"] = "Druk op",
}
