Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["fr"] = {
    ["criminalRecord"] = "Casier Judiciaire",
    ["recordOf"] = "Casier de",
    ["username"] = "Nom de la Personne",
    ["addUpperCase"] = "AJOUTER",
    ["infractionReason"] = "Motif de l'infraction",
    ["create"] = "Creer",
    ["cancel"] = "Annuler",
    ["licenseplate"] = "Plaque D'imatriculation",
    ["search"] = "Rechercher",
    ["noVehiclesFound"] = "Aucun Vehicules Trouvés",
    ["reportText"] = [[Madame, Monsieur le Procureur,

    Je soussigné(e) (nom et prénom), né(e) le date de naissance à lieu de naissance et exerçant la profession de (profession), vous informe porter plainte contre (nom et prénom / nom de l'entreprise / nom de l'organisation / ou X si personne non connue), résidant à (nommer l'adresse de la personne ou de l'entreprise concernée) pour (qualification de l'infraction).

    En date du (date de l'événement), j'ai en effet été victime des faits suivants : (indiquer le plus précisément possible le détail des faits ainsi que le lieu où ils se sont produits, l'heure de l'événement et les personnes impliquées dans l'infraction). Je joins à cette lettre les documents / photos / preuves qui pourraient se révéler utiles dans la suite de cette affaire (attention à joindre des copies et non des originaux).

    Plusieurs personnes ont été témoins de l'infraction mentionnée ci-dessus. Il s'agit de Madame / Monsieur (noms et prénoms).

    Je vous prie d'agréer, Madame, Monsieur le Procureur, l'expression de mes sentiments les meilleurs.

    Signature du Policier]],
    ["unknown"] = "Inconnue",
    ["delete"] = "Delete",
    ["at"] = "Le",
    ["accusedName"] = "Nom de L'Accusé",
    ["save"] = "Save",
    ["prosecutor"] = "Procureur",
    ["accused"] = "Acusé",
    ["date"] = "Date",
    ["see"] = "Voir",
    ["username2"] = "Nom de la Personne",
    ["allComplaints"] = "Toutes les Plaintes",
    ["moveX"] = "Deplacement Axe-X",
    ["moveY"] = "Deplacement Axe-Y",
    ["moveZ"] = "Deplacement Axe-Z",
    ["rotateX"] = "Rotation Axe-X",
    ["rotateY"] = "Rotation Axe-Y",
    ["rotateZ"] = "Rotation Axe-Z",
    ["rotateYY"] = "Rotation Axe-Y",
    ["width"] = "Largeur",
    ["height"] = "Hauteur",
    ["configureLicenseplate"] = "Selectioner le vehicule \n pour configurer la \n plaque d'imatriculation",
    ["placeLicenseplate"] = "Placer la (1) Plaque \n D'imatriculation au bon endroit \n sur votre  vehicule",
    ["placeLicenseplate2"] = "Placer la (2) Plaque \n D'imatriculation au bon endroit \n sur votre  vehicule",
    ["undefined"] = "Vous n'avez pas le bon metier pour ouvrir l'ordinateur",
    ["youWon"] = "Vous avez gagné",
    ["youAddPenality"] = "Vous avez ajouter une penalité",
    ["cameraCenter"] = "Centre Camera",
    ["cameraSecurityOfCity"] = "Camera de Sécurité de la ville",
    ["switchCamera"] = "Appuyé sur [UTILISER] pour changer de camera",
    ["cantDelete"] = "Vous ne pouvez pas supprimer ceci",
    ["cantDoThat"] = "Vous ne pouvez pas faire cela",
    ["noSignal"] = "AUCUN SIGNAL",
    ["connectionProblem"] = "Probleme de Connection",
    ["computerMustBeHacked"] = "l'ordinateur doit être hacké pour ouvrir une application",
    ["cantAffordFine"] = "Vous n'avez pas assez d'argent pour payer l'amende",
    ["payFine"] = "Payer l'Ammende",
    ["confirm"] = "CONFIRMER",
    ["category"] = "CATEGORIE",
    ["fineBook"] = "Carnet D'Ammende",
    ["noPayFine"] = "N'a pas payé l'amende",
    ["personAlreadyHaveFine"] = "Cette personne a déjà une amende",
    ["vehicleHaveFine"] = "Ce vehicule a déjà une amende",
    ["vehicleCantReceiveFine"] = "Ce vehicule ne peut pas avoir d'amende",
    ["noGoodJob"] = "Vous n'avez pas le bon metier pour ajouter une amende",
    ["userCantReceiveFine"] = "Cette personne ne peux pas recevoir d'amende",
    ["vehicleCantHaveFine"] = "Ce vehicule ne peut pas avoir d'amende",
    ["richSanctions"] = "Vous avez atteint la limite de sanction",
    ["mustSelectPenality"] = "Vous devez selectionner une penalité",
    ["cantAddFineToHimVehicle"] = "Vous ne pouvez pas ajouter une amende a votre vehicule",
    ["noGoodJobToArrestuser"] = "Vous n'avez pas le bon metier pour arreter cette personne",
    ["cantArrestPlayer"] = "Vous ne pouvez pas arreter cette personne",
    ["needHoldPlayerToArrest"] = "Vous devez tenir une personne pour le mettre en prison",
    ["justPaid"] = "Vous venez de payer",
    ["cantAfford"] = "Vous n'avez pas assez d'argent pour faire ceci",
    ["arrestMenu"] = "Menu d'Arrestation",
    ["name"] = "Nom",
    ["price"] = "Prix",
    ["reason"] = "Motif",
    ["pay"] = "Payer",
    ["arrestedPlayersList"] = "Liste des Prisonniers",
    ["noArrestedPlayer"] = "Aucune personne n'est arretée",
    ["noJailPositions"] = "Il n'y a aucune position de prison contacté un administrateur",
    ["weaponsList"] = "Liste des Armes",
    ["confiscate"] = "CONFISQUER",
    ["youSurrender"] = "Vous vous rendez",
    ["youArrest"] = "Vous êtes arreté",
    ["years"] = "Années",
    ["tooMuchEntities"] = "Vous avez trop d'entités",
    ["spawnPropText"] = "Appuyez sur [UTILISER] pour faire spawn le prop",
    ["youUnarrestBy"] = "Vous avez été liberé par",
    ["youArrestBy"] = "Vous avez été arreté par",
    ["youHaveArrest"] = "Vous avez arreté",
    ["policeCartrunk"] = "Coffre de Police",
    ["cantDeleteSelfSanctions"] = "Vous ne pouvez pas supprimer une de vos sanctions",
    ["cantEditSelfSanctions"] = "Vous ne pouvez pas editer une de vos sanctions",
    ["seconds"] = "Secondes",
    ["cameraName"] = "Nom de la Camera",
    ["cameraConfiguration"] = "Configuration Camera",
}