Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["tr"] = {
    ["criminalRecord"] = "Sabika Kaydi",
    ["recordOf"] = "Dolap sahibi",
    ["username"] = "Kisinin Ismi",
    ["addUpperCase"] = "EKLE",
    ["infractionReason"] = "Sucun nedeni",
    ["create"] = "Olustur",
    ["cancel"] = "Iptal Et",
    ["licenseplate"] = "Plaka",
    ["search"] = "Ara",
    ["noVehiclesFound"] = "Hicbir arac bulunamadi",
    ["reportText"] = [[Bayan, Bay. Savci,

    Ben asagida imzasi bulunan (Isim ve soy isim), (Dogum yeri ve dogum gunu) dogan ve meslegi (mesleginiz) olan bir sikayetciyim. Bu vesile ile (Isim ve Soyisim / sirket ismi / organizasyon ismi / veya bilinmiyorsa X), (sirketin veya sahisin adresi)'nde ikamet eden ve (sucun niteligi).

    (olayin tarihi) tarihinde gerceklesen bu olaydan sikayetciyim, Bu olayin kurbani oldugumu su sebeplerle gostereyim: (yasanan olayi tum detaylarla, mekan isimleri,saatiyle beraber her detayına kadar yazin). Bu davanin kisa surmesinde yardimci olan dokuman/fotograf/kanit ve benzeri dokumanlari suraya birakiyorum  (lutfen fotograflari buraya yerlestiriniz).

    Asagida adi gecen birkac sahis olaya taniklik etmislerdir. Bunlar Bay/Bayan (tam adlari), (tanikin istikamet ettigi yer)'da istikamet ediyorlar ve su numaradan ulasilabilir (tanikin telefon numarasi).

    Asagida adi gecen birkac sahis olaya taniklik etmislerdir. Bunlar Bay / Bayan (isim ve soy isimleri).

    Lutfen bu davayi cozmenizi rica ediyorum, Bayan, Bay Savci, size sans dileyip tesekkur ediyorum, iyi gunler.

    Polis Memurunun Imzasi]],
    ["unknown"] = "Bilinmeyen",
    ["delete"] = "Sil",
    ["at"] = "The",
    ["accusedName"] = "Sanik Adi",
    ["save"] = "Kaydet",
    ["prosecutor"] = "Savci",
    ["accused"] = "Taninan",
    ["date"] = "Tarih",
    ["see"] = "Goz At",
    ["username2"] = "Kisinin ismi",
    ["allComplaints"] = "Tum sikayetler",
    ["moveX"] = "Yerlestirmenin X-ekseni",
    ["moveY"] = "Yerlestirmenin Y-ekseni",
    ["moveZ"] = "Yerlestirmenin Z-ekseni",
    ["rotateX"] = "Donmenin X-ekseni",
    ["rotateY"] = "Donmenin Y-ekseni",
    ["rotateZ"] = "Donmenin Z-ekseni",
    ["rotateYY"] = "Donmenin Y-ekseni",
    ["width"] = "Genislik",
    ["height"] = "Yukseklik",
    ["configureLicenseplate"] = "Plakayi yapilandirmak \n icin bir arac seciniz",
    ["placeLicenseplate"] = "Plakayi (1) aracin guzel \n ve gorunulebilir yerine \n yerlestirin",
    ["placeLicenseplate2"] = "Plakayi (2) aracin guzel \n ve gorunulebilir yerine \n yerlestirin",
    ["undefined"] = "Bilgisayara erişmek için doğru işiniz yok",
    ["youWon"] = "Kazandin",
    ["youAddPenality"] = "Bir ceza ekledin",
    ["cameraCenter"] = "Kamera Merkezi",
    ["cameraSecurityOfCity"] = "Sehirin guvenlik kamerasi",
    ["switchCamera"] = "Kamerayi degistirmek icin kullan tusuna basin",
    ["cantDelete"] = "Bunu silemezsin",
    ["cantDoThat"] = "Bunu yapamazsin",
    ["noSignal"] = "SINYAL YOK",
    ["connectionProblem"] = "Baglantida bir problem var",
    ["computerMustBeHacked"] = "Bir uygulamayi acmak icin bilgisayari hacklemen gerekir",
    ["cantAffordFine"] = "Cezayi odemek icin yeterli paran yok",
    ["payFine"] = "Cezayi Ode",
    ["confirm"] = "ONAYLA",
    ["category"] = "KATEGORI",
    ["fineBook"] = "Ceza Defteri",
    ["noPayFine"] = "Para Cezasini Odemedi",
    ["personAlreadyHaveFine"] = "Bu sahis adina zaten bir para cezasi kesilmis durumda",
    ["vehicleHaveFine"] = "Bu arac adina zaten bir para cezasi kesilmis durumda",
    ["vehicleCantReceiveFine"] = "Bu araca ceza kesemezsiniz",
    ["noGoodJob"] = "Ceza eklemek icin dogru meslekte degilsiniz",
    ["userCantReceiveFine"] = "Bu oyuncuya para cezasi kesemezsin",
    ["vehicleCantHaveFine"] = "Bu araca para cezasi kesemezsin",
    ["richSanctions"] = "Daha fazla ceza kesebilirsin",
    ["mustSelectPenality"] = "Bir ceza secmen lazim",
    ["cantAddFineToHimVehicle"] = "Kendi aracina ceza kesemezsin",
    ["noGoodJobToArrestuser"] = "Bu oyuncuyu tutuklamak icin dogru meslege sahip degilsin",
    ["cantArrestPlayer"] = "Bu oyuncuyu tutuklayamazsin",
    ["needHoldPlayerToArrest"] = "Birini hapise atmak icin suruklemen lazim",
    ["justPaid"] = "Su kadar odedin",
    ["cantAfford"] = "Bunu yapmaya yeterli paran yok",
    ["arrestMenu"] = "Tutuklama Menusu",
    ["name"] = "Isim",
    ["price"] = "Ucret",
    ["reason"] = "Motif",
    ["pay"] = "Ode",
    ["arrestedPlayersList"] = "Tutuklananlarin Listesi",
    ["noArrestedPlayer"] = "Hicbir oyuncu tutuklanmamis",
    ["noJailPositions"] = "Ayarlanmis herhangi bir hapis pozisyonu yok, bir admine ulasin",
    ["weaponsList"] = "Silah Listesi",
    ["confiscate"] = "EL KOY",
    ["youSurrender"] = "Teslim Oldunuz",
    ["youArrest"] = "Tutuklusunuz",
    ["years"] = "Yil",
    ["tooMuchEntities"] = "Birçok varlığa sahipsin",
    ["spawnPropText"] = "Pervaneyi oluşturmak için [USE] tuşuna basın",
    ["youUnarrestBy"] = "Tarafından serbest bırakıldınız",
    ["youArrestBy"] = "Tarafından tutuklandın",
    ["youHaveArrest"] = "Tutukladın",
    ["policeCartrunk"] = "Polis Sandıgı",
    ["cantDeleteSelfSanctions"] = "Penalitesini silemezsin",
    ["cantEditSelfSanctions"] = "Penalitesini düzenleyemezsin",
    ["seconds"] = "saniye",
    ["cameraName"] = "Kamera Adı",
    ["cameraConfiguration"] = "Kamera Yapılandırması",
}