Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["cn"] = {
    ["criminalRecord"] = "犯罪记录",
    ["recordOf"] = "储物柜",
    ["username"] = "姓名",
    ["addUpperCase"] = "添加",
    ["infractionReason"] = "罪行",
    ["create"] = "创建",
    ["cancel"] = "取消",
    ["licenseplate"] = "车牌",
    ["search"] = "搜索",
    ["noVehiclesFound"] = "没有找到车辆",
    ["reportText"] = [[检察官先生/女士，

    本人（姓和名），生于（出生地出生日期），从事（职业），特此通知你对居住在（有关人员或公司的地址名称）的（姓和名/公司名称/组织名称/或X（如不详））进行（犯罪行为）投诉。

    截至(事件发生日期)，本人确实是以下事件的受害者：(请尽可能准确地注明事件的详细情况以及发生地点、事件发生时间和参与犯罪的人员)。我随信附上可能对本案进一步审理有用的任何文件/照片/证据（请附上复印件，不要原件）。

    有几个人目睹了上述犯罪行为。他们是太太/先生（姓和名），住在（证人的地址），可以通过以下号码（证人的电话号码）联系。

    有几个人目睹了上述犯罪行为。他们是夫人/先生（姓和名）。

    检察官先生/女士，请接受我最美好的祝愿，谢谢你，祝你有愉快的一天。

    警务人员签名]],
    ["unknown"] = "未知",
    ["delete"] = "删除",
    ["at"] = "该",
    ["accusedName"] = "被告姓名",
    ["save"] = "保存",
    ["prosecutor"] = "检察官",
    ["accused"] = "已确认",
    ["date"] = "日期",
    ["see"] = "看",
    ["username2"] = "姓名",
    ["allComplaints"] = "所有的投诉",
    ["moveX"] = "X轴位移",
    ["moveY"] = "Y轴位移",
    ["moveZ"] = "Z轴位移",
    ["rotateX"] = "X轴旋转",
    ["rotateY"] = "Y轴旋转",
    ["rotateZ"] = "Z轴旋转",
    ["rotateYY"] = "Y轴旋转",
    ["width"] = "宽度",
    ["height"] = "高度",
    ["configureLicenseplate"] = "选择车辆进行车牌配置。",
    ["placeLicenseplate"] = "把(1)块车牌挂在你车辆的上",
    ["placeLicenseplate2"] = "把(2)块车牌挂在你车辆的上",
    ["undefined"] = "你没有正确的工作来访问computer。",
    ["youWon"] = "你刚刚赢了",
    ["youAddPenality"] = "你增加了一个处罚",
    ["cameraCenter"] = "摄像中心",
    ["cameraSecurityOfCity"] = "市区监控摄像头",
    ["switchCamera"] = "按 使用 键更换摄像头",
    ["cantDelete"] = "你不能删除它",
    ["cantDoThat"] = "你不能这样做",
    ["noSignal"] = "无信号",
    ["connectionProblem"] = "连接错误",
    ["computerMustBeHacked"] = "你必须入侵它才可以打开应用程序。",
    ["cantAffordFine"] = "你没有足够的钱来支付罚款。",
    ["payFine"] = "缴纳罚款",
    ["confirm"] = "确认",
    ["category"] = "类型",
    ["fineBook"] = "罚款书",
    ["noPayFine"] = "没有支付罚款",
    ["personAlreadyHaveFine"] = "这个人已经有罚款了",
    ["vehicleHaveFine"] = "这辆车已经有罚款了",
    ["vehicleCantReceiveFine"] = "不能给这辆车罚款",
    ["noGoodJob"] = "职业错误，不能增加罚单",
    ["userCantReceiveFine"] = "你不能给这名玩家下罚单",
    ["vehicleCantHaveFine"] = "你不能给这辆车下罚单",
    ["richSanctions"] = "你可以增加更多的罚金",
    ["mustSelectPenality"] = "你必须设定罚款金额",
    ["cantAddFineToHimVehicle"] = "你不能给自己的车罚款",
    ["noGoodJobToArrestuser"] = "职业错误，你不能逮捕这个人",
    ["cantArrestPlayer"] = "你不能逮捕这个人",
    ["needHoldPlayerToArrest"] = "你必须抓着玩家才能让他坐牢",
    ["justPaid"] = "你刚付了钱",
    ["cantAfford"] = "你没有足够的钱来做这件事",
    ["arrestMenu"] = "逮捕菜单",
    ["name"] = "名称",
    ["price"] = "价格",
    ["reason"] = "原因",
    ["pay"] = "支付",
    ["arrestedPlayersList"] = "被捕人员名单",
    ["noArrestedPlayer"] = "没有玩家被捕",
    ["noJailPositions"] = "没有设置监狱位置，请联系管理员",
    ["weaponsList"] = "武器列表",
    ["confiscate"] = "充公",
    ["youSurrender"] = "你已投降",
    ["youArrest"] = "你被逮捕了",
    ["years"] = "年",
    ["tooMuchEntities"] = "你有很多实体",
    ["spawnPropText"] = "按[USE]键生成道具",
    ["youUnarrestBy"] = "你被释放了",
    ["youArrestBy"] = "你被逮捕了",
    ["youHaveArrest"] = "逮捕你",
    ["policeCartrunk"] = "警察箱",
    ["cantDeleteSelfSanctions"] = "你不能删除你的惩罚",
    ["cantEditSelfSanctions"] = "你不能编辑你的刑罚",
    ["seconds"] = "秒",
    ["cameraName"] = "相机名称",
    ["cameraConfiguration"] = "相机配置",
}