Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["en"] = {
    ["criminalRecord"] = "Criminal Record",
    ["recordOf"] = "Locker of",
    ["username"] = "Name of the Person",
    ["addUpperCase"] = "ADD",
    ["infractionReason"] = "Reason for the offence",
    ["create"] = "Create",
    ["cancel"] = "Cancel",
    ["licenseplate"] = "License Plate",
    ["search"] = "Search",
    ["noVehiclesFound"] = "No vehicles found",
    ["reportText"] = [[Madam, Mr. Prosecutor,

    I, the undersigned (name and surname), born on date of birth in place of birth and practicing the profession of (profession), inform you that I am filing a complaint against (name and surname / name of the company / name of the organization / or X if unknown), residing at (name the address of the person or company concerned) for (qualification of the offence).

    On (date of the event), I was indeed the victim of the following facts: (indicate as precisely as possible the details of the facts as well as the place where they occurred, the time of the event and the persons involved in the infraction). I enclose with this letter any documents / photos / evidence that may be useful in the future of this case (please attach copies and not originals).

    Several people witnessed the above-mentioned offence. They are Mrs/Mr (first and last names).

    Please accept, Madam, Mr. Prosecutor, the expression of my best feelings.

    Signature of the Police Officer]],
    ["unknown"] = "Unknown",
    ["delete"] = "Delete",
    ["at"] = "The",
    ["accusedName"] = "Accused Name",
    ["save"] = "Save",
    ["prosecutor"] = "Prosecutor",
    ["accused"] = "Acknowledged",
    ["date"] = "Date",
    ["see"] = "See",
    ["username2"] = "Name of the Person",
    ["allComplaints"] = "All complaints",
    ["moveX"] = "Displacement X-axis",
    ["moveY"] = "Displacement Y-axis",
    ["moveZ"] = "Displacement Z-axis",
    ["rotateX"] = "Rotation X-axis",
    ["rotateY"] = "Rotation Y-axis",
    ["rotateZ"] = "Rotation Z-axis",
    ["rotateYY"] = "Rotation Y-axis",
    ["width"] = "Width",
    ["height"] = "Height",
    ["configureLicenseplate"] = "Select the vehicle \n for configure the \n license plate",
    ["placeLicenseplate"] = "Place the (1) License \n Plate in the good place \n of your vehicle",
    ["placeLicenseplate2"] = "Place the (2) License \n Plate in the good place \n of your vehicle",
    ["undefined"] = "You don't have the right job to access on the computer",
    ["youWon"] = "You just won",
    ["youAddPenality"] = "You have added a penalty",
    ["cameraCenter"] = "Camera Center",
    ["cameraSecurityOfCity"] = "Security Camera of the City",
    ["switchCamera"] = "Press Use for Change Camera",
    ["cantDelete"] = "You can't delete this",
    ["cantDoThat"] = "You can't do this",
    ["noSignal"] = "NO SIGNAL",
    ["connectionProblem"] = "Problem with the Connexion",
    ["computerMustBeHacked"] = "The computer have to be hacked for open an application",
    ["cantAffordFine"] = "You don't have enough money for pay the fine",
    ["payFine"] = "Pay the Fine",
    ["confirm"] = "CONFIRM",
    ["category"] = "CATEGORY",
    ["fineBook"] = "Fine Book",
    ["noPayFine"] = "Did not pay the fine",
    ["personAlreadyHaveFine"] = "This person have already a fine",
    ["vehicleHaveFine"] = "This vehicle have already a fine",
    ["vehicleCantReceiveFine"] = "This vehicle can't have a fine",
    ["noGoodJob"] = "You don't have the right job for add a fine",
    ["userCantReceiveFine"] = "You can't add a fine to this player",
    ["vehicleCantHaveFine"] = "You can't add fine on this vehicle",
    ["richSanctions"] = "You can add more penalty",
    ["mustSelectPenality"] = "You have to select a penalty",
    ["cantAddFineToHimVehicle"] = "You can't add a fine to your vehicle",
    ["noGoodJobToArrestuser"] = "You don't have the right job to arrest this person",
    ["cantArrestPlayer"] = "You can't arrest this person",
    ["needHoldPlayerToArrest"] = "You must drag a player for jail someone",
    ["justPaid"] = "You just paid",
    ["cantAfford"] = "You don't have enought money for do this",
    ["arrestMenu"] = "Arrest Menu",
    ["name"] = "Name",
    ["price"] = "Price",
    ["reason"] = "Motif",
    ["pay"] = "Pay",
    ["arrestedPlayersList"] = "List of Arrested",
    ["noArrestedPlayer"] = "There is no player arrested",
    ["noJailPositions"] = "There is no jail position contact an administrator",
    ["weaponsList"] = "List of Weapons",
    ["confiscate"] = "CONFISCATE",
    ["youSurrender"] = "You are Surrender",
    ["youArrest"] = "You are Arrested",
    ["years"] = "Years",
    ["tooMuchEntities"] = "You have too many entities",
    ["spawnPropText"] = "Press [USE] to spawn the prop",
    ["youUnarrestBy"] = "You were released by",
    ["youArrestBy"] = "You were arrested by",
    ["youHaveArrest"] = "You arrested",
    ["policeCartrunk"] = "Police Trunk",
    ["cantDeleteSelfSanctions"] = "You can't delete your penalty",
    ["cantEditSelfSanctions"] = "You can't edit your penalty",
    ["seconds"] = "Seconds",
    ["cameraName"] = "Name of the Camera",
    ["cameraConfiguration"] = "Camera Configuration",
}
