Realistic_Police = Realistic_Police or {}
Realistic_Police.Language = Realistic_Police.Language or {}

Realistic_Police.Language["es"] = {
    ["criminalRecord"] = "Antecedentes",
    ["recordOf"] = "Taquilla de",
    ["username"] = "Nombre de la persona",
    ["addUpperCase"] = "AÑADIR",
    ["infractionReason"] = "Motivo de la infracción",
    ["create"] = "Crear",
    ["cancel"] = "Cancelar",
    ["licenseplate"] = "Matrícula",
    ["search"] = "Buscar",
    ["noVehiclesFound"] = "No se han encontrado vehículos",
    ["reportText"] = [[Señora, Señor Fiscal,

    Yo, el abajo firmante (apellidos y nombre), nacido el (fecha de nacimiento en el lugar de nacimiento) y que ejerzo la profesión de (profesión), le comunico que presento una denuncia contra (apellidos y nombre / nombre de la empresa / nombre de la organización / o X si se desconoce), con domicilio en (indicar la dirección de la persona o empresa en cuestión) por (calificación del delito).

    En efecto, a partir de (fecha del hecho), he sido víctima de los siguientes hechos: (indicar con la mayor precisión posible los detalles de los hechos, así como el lugar donde ocurrieron, la hora del suceso y las personas implicadas en el delito). Adjunto a la presente los documentos/fotografías/pruebas que puedan ser de utilidad en el curso posterior de este caso (adjuntar copias y no originales).

    Varias personas fueron testigos de la infracción mencionada. Son la Sra./el Sr. (nombres y apellidos), residen en (dirección de los testigos) y pueden ser localizados en el siguiente número (número de teléfono de los testigos).

    Varias personas presenciaron la infracción mencionada. Son la Sra./el Sr. (apellidos y nombre).

    Firma del agente de policía]],
    ["unknown"] = "Desconocido",
    ["delete"] = "Eliminar",
    ["at"] = "En",
    ["accusedName"] = "Nombre del acusado",
    ["save"] = "Guardar",
    ["prosecutor"] = "Fiscal",
    ["accused"] = "Reconocido",
    ["date"] = "Fecha",
    ["see"] = "Ver",
    ["username2"] = "Nombre de la persona",
    ["allComplaints"] = "Todas las denuncias",
    ["moveX"] = "Desplazamiento Eje X",
    ["moveY"] = "Desplazamiento Eje Y",
    ["moveZ"] = "Desplazamiento Eje Z",
    ["rotateX"] = "Rotación eje X",
    ["rotateY"] = "Rotación eje Y",
    ["rotateZ"] = "Rotación eje Z",
    ["rotateYY"] = "Rotación eje Y",
    ["width"] = "Anchura",
    ["height"] = "Altura",
    ["configureLicenseplate"] = "Seleccione el vehículo \n para configurar la \n matrícula",
    ["placeLicenseplate"] = "Coloque la (1) matrícula \n en el lugar adecuado \n de su vehículo",
    ["placeLicenseplate2"] = "Coloque la (2) matrícula \n en el lugar adecuado \n de su vehículo",
    ["undefined"] = "No tienes el trabajo adecuado para acceder al ordenador",
    ["youWon"] = "Acabas de ganar",
    ["youAddPenality"] = "Ha añadido una sanción",
    ["cameraCenter"] = "Centro de cámaras",
    ["cameraSecurityOfCity"] = "Cámara de seguridad de la ciudad",
    ["switchCamera"] = "Pulse [Usar] para Cambiar Cámara",
    ["cantDelete"] = "No puedes eliminar esto",
    ["cantDoThat"] = "No puedes hacer esto",
    ["noSignal"] = "SIN SEÑAL",
    ["connectionProblem"] = "Problema con la conexión",
    ["computerMustBeHacked"] = "Hay que piratear el ordenador para abrir una aplicación",
    ["cantAffordFine"] = "No tienes suficiente dinero para pagar la multa",
    ["payFine"] = "Pagar la multa",
    ["confirm"] = "CONFIRMAR",
    ["category"] = "CATEGORÍA",
    ["fineBook"] = "Libro de multas",
    ["noPayFine"] = "No pagó la multa",
    ["personAlreadyHaveFine"] = "Esta persona ya tiene una multa",
    ["vehicleHaveFine"] = "Este vehículo ya tiene una multa",
    ["vehicleCantReceiveFine"] = "Este vehículo no puede tener una multa",
    ["noGoodJob"] = "No tienes el trabajo adecuado para añadir una multa",
    ["userCantReceiveFine"] = "No se puede añadir una multa a este jugador",
    ["vehicleCantHaveFine"] = "No se puede añadir multa en este vehículo",
    ["richSanctions"] = "Puede añadir más sanciones",
    ["mustSelectPenality"] = "Tienes que seleccionar una sanción",
    ["cantAddFineToHimVehicle"] = "No puedes añadir una multa a tu vehículo",
    ["noGoodJobToArrestuser"] = "No tienes el trabajo adecuado para detener a esta persona",
    ["cantArrestPlayer"] = "No puedes arrestar a esta persona",
    ["needHoldPlayerToArrest"] = "Debes arrastrar al jugador para encarcelarle",
    ["justPaid"] = "Acabas de pagar",
    ["cantAfford"] = "No tienes suficiente dinero para hacer esto",
    ["arrestMenu"] = "Menú de arrestos",
    ["name"] = "Nombre",
    ["price"] = "Precio",
    ["reason"] = "Motivo",
    ["pay"] = "Pagar",
    ["arrestedPlayersList"] = "Lista de arrestados",
    ["noArrestedPlayer"] = "No hay ningún jugador arrestado",
    ["noJailPositions"] = "No hay ninguna celda posicionada, contacte con un administrador",
    ["weaponsList"] = "Lista de armas",
    ["confiscate"] = "CONFISCAR",
    ["youSurrender"] = "Te has rendido",
    ["youArrest"] = "Estas arrestado",
    ["years"] = "Años",
    ["tooMuchEntities"] = "Tienes muchas entidades",
    ["spawnPropText"] = "Pulsa [USAR] para spawnear el prop",
    ["youUnarrestBy"] = "Has sido liberado por",
    ["youArrestBy"] = "Has sido arrestado por",
    ["youHaveArrest"] = "Estas arrestado",
    ["policeCartrunk"] = "Maletero policial",
    ["cantDeleteSelfSanctions"] = "No puedes eliminar tu sanción",
    ["cantEditSelfSanctions"] = "No puedes editar tu sanción",
    ["seconds"] = "Segundos",
    ["cameraName"] = "Nombre de la cámara",
    ["cameraConfiguration"] = "Configuración de la cámara",
}
