local oLocale = ZCLocale:New("en")
oLocale:SetLabel("English")

oLocale:SetDictionnary({
    ["generic.back"] = "Back",
    ["generic.edit"] = "Edit",
    ["generic.close"] = "Close",
    ["generic.confirm"] = "Confirm",
    ["generic.add"] = "Add",
    ["generic.delete"] = "Delete",
    ["generic.destroy"] = "Destroy",
    ["generic.shift_delete"] = "Hold [Shift] to bypass confirmation",
    ["generic.map"] = "Map",
    ["generic.volume"] = "Volume",
    ["generic.volume_format"] = "%s m3",
    ["generic.yes"] = "Yes",
    ["generic.no"] = "No",
    ["generic.no_permission"] = "You don't have permission to do that",
    ["generic.enable"] = "Enable",
    ["generic.disable"] = "Disable",
    ["generic.enabled"] = "Enabled",
    ["generic.disabled"] = "Disabled",
    ["generic.limit_reached"] = "Limit reached",
    ["generic.rename"] = "Rename",
    ["generic.unknown"] = "Unknown",
    ["generic.player"] = "Player",
    ["generic.angle"] = "Angle",
    ["generic.label"] = "Label",
    ["generic.usergroups"] = "User Groups",
    ["generic.modifiers"] = "Modifiers",
    ["generic.roles"] = "Roles",

    ["menutabs.dashboard.title"] = "Dashboard",
    ["menutabs.dashboard.description"] = "View your zones and activities",
    ["menutabs.managezones.title"] = "Manage Zones",
    ["menutabs.managezones.description"] = "Manage your zones, edit them, delete them or create new ones",
    ["menutabs.settings.title"] = "Settings",
    ["menutabs.settings.description"] = "Manage your settings",
    ["menutabs.roles.title"] = "Roles",
    ["menutabs.roles.description"] = "Roles are used to group members and assign them permissions",
    ["menutabs.tutorial.title"] = "Tutorial",
    ["menutabs.tutorial.description"] = "Get started with the tutorial",
    ["menutabs.housekeeping.title"] = "Housekeeping",
    ["menutabs.housekeeping.description"] = "Maintenance Utilities",
    ["menutabs.help.title"] = "Help & Support",
    ["menutabs.help.description"] = "Get help and support",
    ["menutabs.editrole.title"] = "Edit Role",
    ["menutabs.editrole.description"] = "Edit a role",
    ["menutabs.editzone.title"] = "Edit Zone",
    ["menutabs.editzone.description"] = "Edit a zone",

    ["dashboard.title"] = "Welcome %s!",
    ["dashboard.subtitle"] = "Here's a quick overview of your zones settings and activities",
    ["dashboard.zones.title"] = "Zones",
    ["dashboard.zones.subtitle"] = "%s/%s zones in the database",
    ["dashboard.zones.total"] = "Total Zones",
    ["dashboard.zones.enabled"] = "Enabled Zones",
    ["dashboard.zones.yours"] = "Your Zones",
    ["dashboard.zones.current_map"] = "Map Zones",
    ["dashboard.zones.other_maps"] = "Other Maps Zones",
    ["dashboard.modifiers.subtitle"] = "%s/%s modifiers in the database",
    ["dashboard.modifiers.total"] = "Total Modifiers",
    ["dashboard.modifiers.enabled"] = "Enabled Modifiers",
    ["dashboard.roles.title"] = "Roles",
    ["dashboard.roles.subtitle"] = "%s/%s roles in the database",
    ["dashboard.roles.total"] = "Total Roles",
    ["dashboard.roles.admin"] = "Admin Roles",

    ["managezones.searchar.placeholder"] = "Search Zones... (By name, SteamID64, map or date)",
    ["managezones.sort.label"] = "Sort",
    ["managezones.sort.description"] = "Select Order",
    ["managezones.sort.option.date"] = "Sort by Creation Date",
    ["managezones.sort.option.name"] = "Sort by Zone Name",
    ["managezones.sort.option.map"] = "Sort by Map Name",
    ["managezones.sort.option.volume"] = "Sort by Volume",
    ["managezones.sort.option.modifiers"] = "Sort by Modifiers Count",
    ["managezones.source.label"] = "Source",
    ["managezones.source.description"] = "Select Source",
    ["managezones.source.option.all"] = "All Sources",
    ["managezones.source.option.yours"] = "Yours",
    ["managezones.source.option.others"] = "Others",
    ["managezones.state.label"] = "State",
    ["managezones.state.description"] = "Select State",
    ["managezones.state.option.all"] = "All States",
    ["managezones.maps.label"] = "Maps",
    ["managezones.maps.description"] = "Select Map(s)",
    ["managezones.maps.option.all"] = "All Maps",
    ["managezones.maps.option.current"] = "Current Map",
    ["managezones.maps.option.others"] = "Other Maps",
    ["managezones.createzone.label"] = "New",
    ["managezones.createzone.description"] = "Create a new zone",
    ["managezones.createzone.option.from_tool"] = "From tool",
    ["managezones.createzone.option.around_player"] = "Around player",
    ["managezones.createzone.around_player.modal.title"] = "Create zone around player?",
    ["managezones.createzone.around_player.modal.subtitle"] = "This will create a zone around the player selected",
    ["managezones.createzone.around_player.modal.size_around"] = "Size (Around player)",
    ["managezones.createzone.around_player.modal.size_above"] = "Size (Above player)",
    ["managezones.createzone.around_player.modal.size_below"] = "Size (Below player)",
    ["managezones.createzone.around_player.modal.create"] = "Create Zone",
    ["managezones.createzone.around_player.modal.invalid_player"] = "The player selected isn't valid anymore",
    ["managezones.empty_list"] = "There are no zones on this server yet\nClick the \"New\" button to create one.",
    ["managezones.no_results"] = "No results with the following filter: \"%s\"",
    ["managezones.no_results_with_options"] = "No results with the selected options",
    ["managezones.zones_visibility.label"] = "Zones Visibility",
    ["managezones.zones_per_page.label"] = "Zones per page",

    ["editzone.general.tabs.general"] = "General",
    ["editzone.general.zone_infos"] = "Zone Informations",
    ["editzone.general.zone_settings"] = "Zone Settings",
    ["editzone.general.state.title"] = "State",
    ["editzone.general.label.placeholder"] = "Enter zone name here",
    ["editzone.general.rename.success_notif"] = "Zone \"%s\" renamed to \"%s\"",
    ["editzone.general.bounds.title"] = "Bounds",
    ["editzone.general.bounds.button"] = "Redefine bounds",
    ["editzone.general.bounds.error_notif"] = "You can only redefine the bounds of this zone on it's map (%s)",
    ["editzone.general.duplicate.title"] = "Duplicate",
    ["editzone.general.duplicate.button"] = "Duplicate zone",
    ["editzone.general.duplicate.modal.title"] = "Duplicate zone?",
    ["editzone.general.duplicate.modal.subtitle"] = "You're about to duplicate this zone, all its modifiers and keyvalues will also be duplicated.\n\nNote that you will probably have to redefine the zone bounds after duplication.",
    ["editzone.general.duplicate.text_entry.placeholder"] = "Enter zone name here",
    ["editzone.general.duplicate.text_entry.default_value"] = "%s (copy)",
    ["editzone.general.expiration_date.title"] = "Expiration Date",
    ["editzone.general.expiration_date.none"] = "No expiration date",
    ["editzone.general.expiration_date.changed_notif"] = "Expiration date changed to %s",
    ["editzone.general.expiration_date.removed_notif"] = "Expiration date removed",
    ["editzone.general.destroy_on_expiry.title"] = "Expiry Action",
    ["editzone.general.destroy_on_expiry.destroy"] = "Destroy on Expiry",
    ["editzone.general.destroy_on_expiry.disable"] = "Disable on Expiry",
    ["editzone.general.keyvalues.title"] = "KeyValues",
    ["editzone.general.keyvalues.subtitle"] = "KeyValues are added on the Zone objet and on the trigger entity. This is meant to be used by developers in third-party scripts.\nYou can ignore it if you don't have any use for it.",
    ["editzone.general.keyvalues.key"] = "Key",
    ["editzone.general.keyvalues.value"] = "Value",
    ["editzone.general.keyvalues.new"] = "Add new KeyValue",
    ["editzone.general.keyvalues.new_key"] = "New Key",
    ["editzone.general.keyvalues.new_value"] = "New Value",
    ["editzone.general.keyvalues.missing_key"] = "Missing key",
    ["editzone.general.keyvalues.missing_value"] = "Missing value",
    ["editzone.general.keyvalues.override.title"] = "KeyValue already exists",
    ["editzone.general.keyvalues.override.subtitle"] = "Are you sure you want to overwrite this KeyValue?\nThis will delete the existing one and replace it with the new one.",
    ["editzone.general.keyvalues.zone_keyvalues"] = "Zone KeyValues",
    ["editzone.general.keyvalues.set_notif"] = "Key/Value \"%s\" set to \"%s\"",
    ["editzone.general.keyvalues.removed_notif"] = "Key/Value \"%s\" removed",
    ["editzone.general.delete.modal.title"] = "Delete zone?",
    ["editzone.general.delete.modal.subtitle"] = "Are you sure you want to delte this zone?\nThis Action cannot be undone.",
    ["editzone.general.delete.success_notif"] = "Zone \"%s\" deleted",
    ["editzone.modifiers.searchbar_placeholder"] = "Search modifiers...",
    ["editzone.modifiers.add"] = "Add modifier",
    ["editzone.modifiers.no_modifiers"] = "No modifiers yet\nclick the \"%s\" button to add one",

    ["zonecard.added_on"] = "Added on",
    ["zonecard.added_on_format"] = "%d %b %Y at %H:%M",
    ["zonecard.created_by"] = "Created by",
    ["zonecard.teleport"] = "Teleport",
    ["zonecard.vis_on"] = "Show on map",
    ["zonecard.vis_off"] = "Hide on map",
    ["zonecard.paste_duplicated_modifier"] = "Duplicate copied modifier",
    ["zonecard.modifiers_count"] = "%s modifier(s)",
    ["zonecard.players_inside"] = "%s player(s) inside",
    ["zonecard.expiration.destroy_in"] = "Will be destroyed in %s",
    ["zonecard.expiration.disable_in"] = "Will be disabled in %s",

    ["modifier.duplicate"] = "Duplicate modifier",
    ["modifier.toggle"] = "Toggle modifier",
    ["modifier.enabled"] = "Modifier \"%s\" enabled on this zone",
    ["modifier.disabled"] = "Modifier \"%s\" disabled on this zone",

    ["roles.header.searchbar.placeholder"] = "Search roles...",
    ["roles.header.createrole"] = "Create new Role",
    ["roles.header.description"] = "Roles that are higher in the hierarchy will have more permissions.\nDrag and drop roles to reorder them.\nSuperAdmin users can bypass all restrictions.",
    ["roles.modal.title"] = "Create Role",
    ["roles.modal.subtitle"] = "Type the name of the role you want to create, then press the confirm button",
    ["roles.list.teams"] = "Teams",
    ["roles.list.players"] = "Players",
    ["roles.list.empty"] = "No roles yet\nClick the \"%s\" button to create one",

    ["editrole.tabs.general"] = "General",
    ["editrole.tabs.permissions"] = "Permissions",
    ["editrole.search_permissions"] = "Search Permissions",
    ["editrole.name.title"] = "Role Name",
    ["editrole.name.placeholder"] = "Type role name here",
    ["editrole.name.empty"] = "Role name cannot be empty",
    ["editrole.name.exists"] = "There is already a role with that name",
    ["editrole.usergroups.subtitle"] = "Players with these groups will have this role",
    ["editrole.usergroups.placeholder"] = "Search User Groups",
    ["editrole.usergroups.add"] = "Add User Group",
    ["editrole.usergroups.add_modal.title"] = "Add User Group",
    ["editrole.usergroups.add_modal.subtitle"] = "Type the name of user group to add to this role",
    ["editrole.usergroups.add_combobox.title"] = "Select a usergroup...",
    ["editrole.usergroups.remove_modal.title"] = "Remove User Group",
    ["editrole.usergroups.remove_modal.subtitle"] = "Are you sure you want to remove user group \"%s\" from the role \"%s\"?",
    ["editrole.teams.title"] = "Teams",
    ["editrole.teams.subtitle"] = "Players with these teams will have this role",
    ["editrole.teams.placeholder"] = "Search Teams",
    ["editrole.teams.add"] = "Add Team",
    ["editrole.teams.add_modal.title"] = "Add Team",
    ["editrole.teams.add_modal.subtitle"] = "Are you sure you want to add this team to the role?",
    ["editrole.teams.add_combobox.title"] = "Select a team...",
    ["editrole.teams.remove_modal.title"] = "Remove Team",
    ["editrole.teams.remove_modal.subtitle"] = "Are you sure you want to remove team \"%s\" from the role \"%s\"?",
    ["editrole.players.title"] = "Players",
    ["editrole.players.subtitle"] = "Players which have their SteamID64 in this list will have this role",
    ["editrole.players.placeholder"] = "Search Players",
    ["editrole.players.add"] = "Add Player",
    ["editrole.players.add_modal.title"] = "Add Player",
    ["editrole.players.add_modal.subtitle"] = "Type the SteamID64 (17 digits) of the player to add to this role",
    ["editrole.players.remove_modal.title"] = "Remove Player",
    ["editrole.players.remove_modal.subtitle"] = "Are you sure you want to remove player %s (%s) from the role \"%s\"?",
    ["editrole.players.invalid_steamid"] = "Invalid SteamID64",
    ["editrole.players.already_has_role"] = "This player already has this role",
    ["editrole.delete.title"] = "Delete role?",
    ["editrole.delete.subtitle"] = "Are you sure you want to delte this role?\nThis Action cannot be undone.",
    ["editrole.allowed_modifiers.title"] = "Allowed Modifiers",
    ["editrole.allowed_modifiers.subtitle"] = "Modifiers that are allowed to be used by this role",

    ["housekeeping.title"] = "Housekeeping",
    ["housekeeping.subtitle"] = "This tab allows you to clear the specified data for the server and the database.\nThese options are destructive, use it at your own risk.",
    ["housekeeping.modal.subtitle"] = "Be careful, this action cannot be undone.\nTo continue, type the security code and click the \"%s\" button.\n\nSecurity code: %s",
    ["housekeeping.modal.placeholder"] = "Type the security code here",
    ["housekeeping.modal.incorrect_code"] = "The security code you entered is incorrect",
    ["housekeeping.reset_settings.title"] = "Reset settings data",
    ["housekeeping.reset_settings.subtitle"] = "Reset all settings",
    ["housekeeping.reset_settings.success_notif"] = "Settings data has been reset!",
    ["housekeeping.reset_roles.title"] = "Reset roles data",
    ["housekeeping.reset_roles.subtitle"] = "%s roles saved on the database",
    ["housekeeping.reset_roles.success_notif"] = "Roles data has been reset!",
    ["housekeeping.reset_zones.title"] = "Reset zones data",
    ["housekeeping.reset_zones.subtitle"] = "%s zones saved on the database",
    ["housekeeping.reset_zones.success_notif"] = "Zones data has been reset!",

    ["settings.title"] = "Settings",
    ["settings.subtitle"] = "This tab allows you to change the settings for ZoneCreator.",
    ["settings.language.title"] = "Language",
    ["settings.language.subtitle"] = "Change the language of the script, for all players.",
    ["settings.language.select"] = "Select a language",
    ["settings.language.modal.title"] = "Change language?",
    ["settings.language.modal.subtitle"] = "Are you sure you want to change the language to \"%s\"?\nThis will restart the menu.",
    ["settings.commands.title"] = "Chat Commands",
    ["settings.commands.subtitle"] = "Chat Commands allows you to open the menu from any chat command.\nThis will not impact the \"%s\" console command.",
    ["settings.commands.new.placeholder"] = "Type chat command here",
    ["settings.commands.new.confirm"] = "Add Command",
    ["settings.commands.new.missing"] = "Missing chat command",

    ["tutorial.title"] = "Tutorial",
    ["tutorial.subtitle"] = "In this video you will learn how to use ZoneCreator.\nGarry's Mod needs to be on the Chromium (x84-64) branch, otherwise the video won't work.",
    ["tutorial.branch_warning"] = "If you have issues playing this video, change the game's branch in Steam settings or open it in Steam's browser.",
    ["tutorial.open_in_browser"] = "Open in Steam browser",

    ["tool.name"] = "Zone Creator Tool",
    ["tool.desc"] = "Allows you to create/edit zone(s)",
    ["tool.left"] = "Select Option",
    ["tool.right"] = "Next Option",
    ["tool.reload"] = "Clear",
    ["tool.options.1.label"] = "Create/Edit Zone",
    ["tool.options.1.edit_zone"] = "Edit Zone",
    ["tool.options.1.create_zone"] = "New Zone",
    ["tool.options.1.step1"] = "Place the minimum corner",
    ["tool.options.1.step2"] = "Place the maximum corner",
    ["tool.options.1.step3"] = "Save",
    ["tool.options.1.create_zone.title"] = "Create zone?",
    ["tool.options.1.create_zone.subtitle"] = "Are you sure you want to create this zone?",
    ["tool.options.1.edit_bounds.title"] = "Save new bounds?",
    ["tool.options.1.edit_bounds.subtitle"] = "Are you sure you want to save the new bounds of \"%s\"?",
    ["tool.options.2.label"] = "Menu",
    ["tool.options.2.description"] = "Open zone manger menu",
    ["tool.options.3.label"] = "Zones Visibility",
    ["tool.options.3.description"] = "Toggle zones visibility",

    ["permissions.is_admin.label"] = "Administrator",
    ["permissions.is_admin.description"] = "Members with this permission will have all permissions, and will be able to bypass any other permission or restriction.",
    ["permissions.open_menu.label"] = "Open Menu",
    ["permissions.open_menu.description"] = "Allows members to open the zone manager menu.",
    ["permissions.manage_roles.label"] = "Manage Roles",
    ["permissions.manage_roles.description"] = "Allows members to create, edit or delete roles lower than their role.",
    ["permissions.manage_settings.label"] = "Manage Settings",
    ["permissions.manage_settings.description"] = "Allows members to access the settings tab and to edit the settings of the script.",
    ["permissions.manage_zones.label"] = "Manage Zones",    
    ["permissions.manage_zones.description"] = "Allows members to create new zones or edit existing zones.",
    ["permissions.manage_zones_state.label"] = "Manage Zones State",
    ["permissions.manage_zones_state.description"] = "Allows members to enable/disable zones and edit modifiers when the zone is enabled.",
    ["permissions.teleport_to_zone.label"] = "Teleport To Zone",
    ["permissions.teleport_to_zone.description"] = "Allows you to teleport to a zone.",

    -- Modifiers
    ------------------------------------------------------------------
    ["modifiers.defaultvars.bind_hook.label"] = "Event",
    ["modifiers.defaultvars.bind_hook.description"] = "Event trigger for this modifier",
    ["modifiers.defaultvars.delay.label"] = "Delay",
    ["modifiers.defaultvars.delay.description"] = "Delay before considering the player as entering the zone",

    ["modifiers.bind_hook.playerdeath.label"] = "Player Death",
    ["modifiers.bind_hook.entitytakedamage.label"] = "On Take Damage",
    ["modifiers.bind_hook.onplayerenterzone.label"] = "On Enter Zone",
    ["modifiers.bind_hook.onplayerleavezone.label"] = "On Leave Zone",

    ["modifiers.armor_mut.label"] = "Armor (Mutator)",
    ["modifiers.armor_mut.description"] = "Changes the armor over time",
    ["modifiers.armor_mut.vars.value.label"] = "Armor Level",
    ["modifiers.armor_mut.vars.value.description"] = "Adds this value to the player's armor every `Duration` seconds \nTo remove armor use a negative value",
    ["modifiers.armor_mut.vars.time.label"] = "Duration",
    ["modifiers.armor_mut.vars.time.description"] =  "Time before armor is added/removed, in seconds",

    ["modifiers.armor.label"] = "Armor (Set)",
    ["modifiers.armor.description"] = "Sets the player's armor",
    ["modifiers.armor.vars.value.label"] = "Armor Level",
    ["modifiers.armor.vars.value.description"] = "Sets the player's armor to this value",

    ["modifiers.audio.label"] = "Audio",
    ["modifiers.audio.description"] = "Plays audio",
    ["modifiers.audio.vars.source.label"] = "Audio Source",
    ["modifiers.audio.vars.source.description"] = "File path (relative to /garrysmod folder) or URL",
    ["modifiers.audio.vars.source.placeholder"] = "Type the path here",
    ["modifiers.audio.vars.loop.label"] = "Enable Looping",
    ["modifiers.audio.vars.loop.description"] = "If enabled, the audio will loop forever",
    ["modifiers.audio.vars.volume.label"] = "Volume",
    ["modifiers.audio.vars.volume.description"] = "Sets the volume of the audio\n0.5 = 50%, 1 = 100%, etc.",
    ["modifiers.audio.vars.sound_time.label"] = "Duration",
    ["modifiers.audio.vars.sound_time.description"] = "Time it takes for the audio to play in seconds, before stopping or switching to the next audio in the queue",
    ["modifiers.audio.vars.queue_order.label"] = "Queue Order",
    ["modifiers.audio.vars.queue_order.description"] = "Determines the order in which the audio is added in the playlist (lower number = higher priority)\n0 = Don't play in queue",
    ["modifiers.audio.vars.fade_in.label"] = "Fade-in Time",
    ["modifiers.audio.vars.fade_in.description"] = "Time it takes for the audio to fade-in to full volume in seconds",
    ["modifiers.audio.vars.fade_out.label"] = "Fade-out Time",
    ["modifiers.audio.vars.fade_out.description"] = "Time it takes for the audio to fade-out to silence in seconds",
    ["modifiers.audio.vars.style.label"] = "Equalizer HUD Style",
    ["modifiers.audio.vars.alpha.label"] = "Equalizer HUD Alpha",
    ["modifiers.audio.vars.alpha.description"] = "0 = transparent\n50 = semi-transparent\n100 = opaque",

    ["modifiers.block.label"] = "Block Volume",
    ["modifiers.block.description"] = "Makes the zone prevent players (or all entities) from entering",
    ["modifiers.block.vars.block_all.label"] = "Block all entities",
    ["modifiers.block.vars.block_all.description"] = "If enabled, the zone will block all entities, not just players",

    ["modifiers.chat_msg.label"] = "Chat Message",
    ["modifiers.chat_msg.description"] = "Sends a chat message to the player",
    ["modifiers.chat_msg.vars.msg.label"] = "Message",
    ["modifiers.chat_msg.vars.msg.description"] = "The message to send",
    ["modifiers.chat_msg.vars.msg.placeholder"] = "Type your message here",

    ["modifiers.give_dmg.label"] = "Damage Given",
    ["modifiers.give_dmg.description"] = "Changes the given damage multiplier",
    ["modifiers.give_dmg.vars.enabled.label"] = "Enabled",
    ["modifiers.give_dmg.vars.enabled.description"] = "Enable damages given",
    ["modifiers.give_dmg.vars.mul.label"] = "Damage Multiplier",
    ["modifiers.give_dmg.vars.mul.description"] = "1 = normal damage, 0.5 = half damage, etc.",

    ["modifiers.take_dmg.label"] = "Damage Received",
    ["modifiers.take_dmg.description"] = "Changes the received damage multiplier",
    ["modifiers.take_dmg.vars.enabled.label"] = "Enabled",
    ["modifiers.take_dmg.vars.enabled.description"] = "Enable damages received",
    ["modifiers.take_dmg.vars.mul.label"] = "Damage Multiplier",
    ["modifiers.take_dmg.vars.mul.description"] = "1 = normal damage, 0.5 = half damage, etc.",

    ["modifiers.exit_veh.label"] = "Exit Vehicle",
    ["modifiers.exit_veh.description"] = "Makes the player exit it's vehicle",
    ["modifiers.exit_veh.exit_vehicle_in"] = "Exit vehicle in %s",

    ["modifiers.engine.label"] = "Engine",
    ["modifiers.engine.description"] = "Start or stop the player's vehicle engine",
    ["modifiers.engine.vars.start.label"] = "Start/stop engine",
    ["modifiers.engine.vars.start.description"] = "Enabled : Start the engine\nDisabled : Stop the engine",

    ["modifiers.fall_dmg.label"] = "Fall Damage",
    ["modifiers.fall_dmg.description"] = "Changes the fall damage multiplier",
    ["modifiers.fall_dmg.vars.enabled.label"] = "Enabled",
    ["modifiers.fall_dmg.vars.enabled.description"] = "Enable fall damages",
    ["modifiers.fall_dmg.vars.mul.label"] = "Fall Damage Multiplier",
    ["modifiers.fall_dmg.vars.mul.description"] = "1 = normal fall damage, 0.5 = half fall damage, etc.",

    ["modifiers.friction.label"] = "Friction",
    ["modifiers.friction.description"] = "Changes the friction of the player when sliding against a surface",
    ["modifiers.friction.vars.mul.label"] = "Friction Multiplier",
    ["modifiers.friction.vars.mul.description"] = "1 = normal friction, 0.5 = half friction, etc.",

    ["modifiers.give_weps.label"] = "Give Weapons",
    ["modifiers.give_weps.description"] = "Gives the player the specified weapon(s)",
    ["modifiers.give_weps.vars.weps.label"] = "Weapons",
    ["modifiers.give_weps.vars.weps.description"] = "Class names of weapons that will be given to the player",
    ["modifiers.give_weps.vars.notify.label"] = "Notify on give",
    ["modifiers.give_weps.vars.notify.description"] = "Notify the player with a chat message when weapons are given",
    ["modifiers.give_weps.vars.strip_on_exit.label"] = "Strip on exit",
    ["modifiers.give_weps.vars.strip_on_exit.description"] = "If enabled, strips the given weapons when leaving the zone",
    ["modifiers.give_weps.notify"] = "[%s] Weapon given: %s",

    ["modifiers.gravity.label"] = "Gravity Multiplier",
    ["modifiers.gravity.description"] = "Changes the gravity for the player",
    ["modifiers.gravity.vars.mul.label"] = "Gravity Multiplier",
    ["modifiers.gravity.vars.mul.description"] = "0 = no gravity\n0.5 = half gravity\n1 = normal gravity\n2 = double gravity",

    ["modifiers.health_mut.label"] = "Health (Mutator)",
    ["modifiers.health_mut.description"] = "Changes the player's health over time",
    ["modifiers.health_mut.vars.value.label"] = "Health Level",
    ["modifiers.health_mut.vars.value.description"] = "Health to add/removed",
    ["modifiers.health_mut.vars.time.label"] = "Duration",
    ["modifiers.health_mut.vars.time.description"] = "Time before health is added/removed, in seconds",

    ["modifiers.health.label"] = "Health (Set)",
    ["modifiers.health.description"] = "Sets the player's health",
    ["modifiers.health.vars.value.label"] = "Health Level",
    ["modifiers.health.vars.value.description"] = "Sets the player's health to this value",

    ["modifiers.hud_msg.label"] = "HUD Message",
    ["modifiers.hud_msg.description"] = "Displays a message in the HUD",
    ["modifiers.hud_msg.vars.l1_text.label"] = "1st line Text",
    ["modifiers.hud_msg.vars.l1_text.description"] = "Available string replacements:\n- %volume%\n- %zone%\n- %nick%\n- %player_count",
    ["modifiers.hud_msg.vars.l1_text.placeholder"] = "First line text",
    ["modifiers.hud_msg.vars.l2_text.label"] = "2nd line Text",
    ["modifiers.hud_msg.vars.l2_text.description"] = "Available string replacements:\n- %volume%\n- %zone%\n- %nick%\n- %player_count",
    ["modifiers.hud_msg.vars.l2_text.placeholder"] = "Second line text",
    ["modifiers.hud_msg.vars.l1_size.label"] = "1st line Font Size",
    ["modifiers.hud_msg.vars.l1_size.description"] = "Font size of the first line",
    ["modifiers.hud_msg.vars.l2_size.label"] = "2nd line Font Size",
    ["modifiers.hud_msg.vars.l2_size.description"] = "Font size of the second line",
    ["modifiers.hud_msg.vars.l1_y.label"] = "1st line Y position",
    ["modifiers.hud_msg.vars.l1_y.description"] = "The Y position of the first line, relative to the screen height\n\n0.1 = 10%\n0.5 = 50%\n1 = 100%",
    ["modifiers.hud_msg.vars.l2_y.label"] = "2nd line Y position",
    ["modifiers.hud_msg.vars.l2_y.description"] = "The Y position of the second line, relative to the screen height\n\n0.1 = 10%\n0.5 = 50%\n1 = 100%",
    ["modifiers.hud_msg.vars.time.label"] = "Duration",
    ["modifiers.hud_msg.vars.time.description"] = "Duration of the message in seconds\n0 to remove only on exit (only works for entry messages)",
    ["modifiers.hud_msg.vars.fade_in.label"] = "Fade-in time",
    ["modifiers.hud_msg.vars.fade_in.description"] = "Time it takes for the HUD to fade-in, in seconds",
    ["modifiers.hud_msg.vars.fade_out.label"] = "Fade-out time",
    ["modifiers.hud_msg.vars.fade_out.description"] = "Time it takes for the HUD to fade-out, in seconds",

    ["modifiers.jump_vel.label"] = "Jump Velocity",
    ["modifiers.jump_vel.description"] = "Changes the jump velocity multiplier for the player",
    ["modifiers.jump_vel.vars.mul.label"] = "Jump Multiplier",
    ["modifiers.jump_vel.vars.mul.description"] = "1 = normal jump velocity, 0.5 = half jump velocity, etc.",

    ["modifiers.kill.label"] = "Kill",
    ["modifiers.kill.description"] = "Kills the player",

    ["modifiers.money_mut.label"] = "Money (Mutator)",
    ["modifiers.money_mut.description"] = "Changes the player's money over time",
    ["modifiers.money_mut.vars.value.label"] = "Money",
    ["modifiers.money_mut.vars.value.description"] = "Money to add/removed",
    ["modifiers.money_mut.vars.time.label"] = "Duration",
    ["modifiers.money_mut.vars.time.description"] = "Time before money is added/removed, in seconds",

    ["modifiers.money.label"] = "Money (Set)",
    ["modifiers.money.description"] = "Sets the player's money",
    ["modifiers.money.vars.value.label"] = "Money",
    ["modifiers.money.vars.value.description"] = "Sets the player's money to this value",

    ["modifiers.no_prop.label"] = "Prevent Prop Spawn",
    ["modifiers.no_prop.description"] = "Prevents the player from spawning props while in the zone",

    ["modifiers.push.label"] = "Push Player",
    ["modifiers.push.description"] = "Pushes the player in the opposite direction of their velocity, can be usefull to create trampolines!",
    ["modifiers.push.vars.force.label"] = "Push Force",
    ["modifiers.push.vars.force.description"] = "The force of the push",

    ["modifiers.speak_sv.label"] = "Speak to Server",
    ["modifiers.speak_sv.description"] = "Allows the player to speak to everyone in the server while in the zone, no matter the distance with other players",

    ["modifiers.speak_zone.label"] = "Speak to Zone",
    ["modifiers.speak_zone.description"] = "Allows the player to speak to everyone in the zone, no matter the distance with other players",

    ["modifiers.speed_mul.label"] = "Speed Multiplier",
    ["modifiers.speed_mul.description"] = "Changes the speed multiplier for the player",
    ["modifiers.speed_mul.vars.mul.label"] = "Speed Multiplier",
    ["modifiers.speed_mul.vars.mul.description"] = "1 = normal speed, 2 = twice as fast, etc.",

    ["modifiers.strip_weps.label"] = "Strip Weapons",
    ["modifiers.strip_weps.description"] = "Strips the player's weapons",
    ["modifiers.strip_weps.vars.weps.label"] = "Weapons",
    ["modifiers.strip_weps.vars.weps.description"] = "Class names of weapons that will be removed from the player",
    ["modifiers.strip_weps.vars.return.label"] = "Return Weapons on Exit",
    ["modifiers.strip_weps.vars.return.description"] = "Gives the weapons back to the player when exiting the zone",
    ["modifiers.strip_weps.vars.notify.label"] = "Notify on take/return",
    ["modifiers.strip_weps.vars.notify.description"] = "Notify the player when weapons are taken or returned",
    ["modifiers.strip_weps.strip_notify"] = "[%s] Stripped: %s",
    ["modifiers.strip_weps.return_notify"] = "[%s] Returned: %s",

    ["modifiers.pos_tp.label"] = "Teleport to Position",
    ["modifiers.pos_tp.description"] = "Teleports the player to the specified position",
    ["modifiers.pos_tp.vars.pos.label"] = "Position",
    ["modifiers.pos_tp.vars.pos.description"] = "The Position to teleport the player to (x, y, z)",
})